name: Update Scripts

on:
  schedule:
    - cron:  '0 8 * * *'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: Run a multi-line script
        run: |
          echo $GITHUB_WORKSPACE
          pwd
          git clone git@github.com:microsoft/vscode-dev-containers.git
          cp -r vscode-dev-containers/script-library/*.sh .
          ls
