name: Update Scripts

on:
  schedule:
    - cron:  '0 8 * * *'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: Run a multi-line script
        run: |
          echo $GITHUB_WORKSPACE
          pwd
          git switch -c release
          git clone https://github.com/microsoft/vscode-dev-containers.git
          cp -r vscode-dev-containers/script-library/*.sh .
          rm -rf vscode-dev-containers
          ls -la
          git config --global user.name 'Git Bot'
          git config --global user.email 'bot@noreply.github.com'
          git add .
          git status
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
          git commit -am "Auto updated scripts" && git push origin release || echo "No changes to commit"

